inputSet:
  name: Build_ipreetgs_microService_TXApplication_1702457135148-push-trigger-input-set
  identifier: Build_ipreetgs_microService_TXApplication_1702457135148pushtriggerinputset
  orgIdentifier: default
  projectIdentifier: default_project
  pipeline:
    identifier: Build_ipreetgs_microService_TXApplication_1702457135148
    properties:
      ci:
        codebase:
          build:
            type: branch
            spec:
              branch: <+trigger.branch>
