inputSet:
  name: Build_ipreetgs_microService_TXApplication_1702456960000-push-trigger-input-set
  identifier: Build_ipreetgs_microService_TXApplication_1702456960000pushtriggerinputset
  orgIdentifier: default
  projectIdentifier: default_project
  pipeline:
    identifier: Build_ipreetgs_microService_TXApplication_1702456960000
    properties:
      ci:
        codebase:
          build:
            type: branch
            spec:
              branch: <+trigger.branch>
