inputSet:
  name: Build_ipreetgs_microService_TXApplication_1702881689439-pr-trigger-input-set
  identifier: Build_ipreetgs_microService_TXApplication_1702881689439prtriggerinputset
  orgIdentifier: default
  projectIdentifier: default_project
  pipeline:
    identifier: Build_ipreetgs_microService_TXApplication_1702881689439
    properties:
      ci:
        codebase:
          build:
            type: PR
            spec:
              number: <+trigger.prNumber>
