pipeline:
  projectIdentifier: DemoTx
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: init
        identifier: init
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: init stage
                  identifier: init_stage
                  spec:
                    shell: Sh
                    command: echo hello
        delegateSelectors:
          - linux-docker-delegate
  identifier: Final_TX_blog_pipeline_Clone
  name: Final_TX_blog_pipeline - Clone
  delegateSelectors:
    - docker-delegate
