pipeline:
  name: final
  identifier: final
  projectIdentifier: DemoTx
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1702454216196
        repoName: https://github.com/ipreetgs/microService_TXApplication
        build: <+input>
  stages:
    - stage:
        name: clone repo
        identifier: clone_repo
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: build img
                  identifier: build_img
                  spec:
                    shell: Sh
                    command: docker build -t mailapp Dockerfile-main-app
        delegateSelectors:
          - linux-docker-delegate
